import React, { useCallback, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { RefreshCw } from 'lucide-react';
import { usePreferences } from '../context/PreferencesContext';
import useNewsPulseData from '../hooks/useNewsPulseData';
import useNewsPulseIngestion from '../hooks/useNewsPulseIngestion';
import useNewsPulseListen from '../hooks/useNewsPulseListen';
import Navbar from '../components/Navbar';
import Button from '../components/Button';
import CategoryPill from '../components/CategoryPill';
import IngestionStatus from '../components/IngestionStatus';
import PulseTimeline from '../components/PulseTimeline';
import PulseClusters from '../components/PulseClusters';
import ClusterDrawer from '../components/ClusterDrawer';

// News Pulse: related articles from different outlets, grouped into topic
// clusters by the AI service and shown as a timeline. All data comes from the
// Node backend's /api/news-pulse gateway.
const NewsPulse = () => {
  const { t } = usePreferences();
  // The selected source lives in the URL (?source=), so links, Back/Forward and
  // the navbar link always agree with what the filter shows.
  const [searchParams, setSearchParams] = useSearchParams();
  const source = searchParams.get('source') || '';
  const [openCluster, setOpenCluster] = useState(null);

  const { clusters, timeline, sources, latestByCluster, loadClusters, retryTimeline, reloadAll } = useNewsPulseData(source);

  // Refresh News: trigger -> poll every ~10s -> on COMPLETED reload topics and
  // timeline. Topic ids are regenerated by every ingestion, so an open topic
  // is closed rather than left pointing at an id that no longer exists.
  const ingestion = useNewsPulseIngestion({
    onCompleted: () => {
      setOpenCluster(null);
      reloadAll();
    },
  });

  // Listen buttons (timeline and topic drawer). Audio is only fetched when one
  // is clicked, and plays through the app's global player.
  const listen = useNewsPulseListen();

  const selectSource = (name) => setSearchParams(name ? { source: name } : {}, { replace: true });

  const closeCluster = useCallback(() => setOpenCluster(null), []);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', width: '100%' }}>
      <Navbar />

      <main className="site-container">
        <section
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            alignItems: 'flex-end',
            justifyContent: 'space-between',
            gap: '16px 24px',
            marginBottom: '24px',
            position: 'relative',
            zIndex: 1,
          }}
        >
          <div style={{ flex: '1 1 360px', minWidth: 0 }}>
            <h1
              style={{
                fontSize: 'clamp(26px, 4vw, 36px)',
                fontWeight: 800,
                lineHeight: 1.2,
                color: 'var(--text-main)',
                letterSpacing: '-0.025em',
                margin: '0 0 8px',
              }}
            >
              {t('newsPulse')}
            </h1>
            <p style={{ fontSize: '14px', color: 'var(--text-secondary)', maxWidth: '640px' }}>{t('pulseSubtitle')}</p>
          </div>

          <Button
            icon={RefreshCw}
            onClick={ingestion.start}
            loading={ingestion.isBusy}
            loadingText={t('pulseRefreshing')}
            data-testid="refresh-news"
          >
            {t('pulseRefresh')}
          </Button>
        </section>

        <div style={{ position: 'relative', zIndex: 1 }}>
          <IngestionStatus ingestion={ingestion} />

          <div
            role="group"
            aria-label={t('pulseSourceFilter')}
            data-testid="source-filter"
            style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', marginBottom: '28px' }}
          >
            <CategoryPill label={t('pulseAllSources')} active={!source} onClick={() => selectSource('')} />
            {sources.map((name) => (
              <CategoryPill key={name} label={name} active={source === name} onClick={() => selectSource(name)} />
            ))}
          </div>

          <div className="pulse-layout">
            <PulseTimeline
              key={source || 'all'}
              timeline={timeline}
              source={source}
              listen={listen}
              onClearSource={() => selectSource('')}
              onOpenCluster={setOpenCluster}
              onRetry={retryTimeline}
            />

            <aside className="pulse-topics-col">
              <PulseClusters
                clusters={clusters}
                latestByCluster={latestByCluster}
                activeId={openCluster?.id}
                onSelect={setOpenCluster}
                onRetry={loadClusters}
              />
            </aside>
          </div>
        </div>
      </main>

      {openCluster && <ClusterDrawer key={openCluster.id} cluster={openCluster} listen={listen} onClose={closeCluster} />}
    </div>
  );
};

export default NewsPulse;
